name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: install boost
      if: matrix.os == 'macos-latest'
      run: |
        sudo add-apt-repository ppa:mhier/libboost-latest
        sudo apt-get update
        sudo apt-get install boost1.67
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake ..
    - name: make check_deps
      run: |
        cd build
        make check_deps VERBOSE=1
    - name: make
      run: |
        cd build
        make -j4 VERBOSE=1
    - name: ctest
      run: |
        cd build
        ctest -VV
