name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc, clang]
        exclude:
        - os: macos-latest
          compiler: gcc
    steps:
    - uses: actions/checkout@v1
    - name: install boost for linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo add-apt-repository ppa:mhier/libboost-latest
        sudo apt-get update
        sudo apt-get install boost1.67
    - name: install boost for macos
      if: matrix.os == 'macos-latest'
      run: |
        brew install boost
    - name: cmake
      env:
        CC: ${{ matrix.compiler }}
      run: |
        mkdir build
        cd build
        cmake ..
    - name: make check_deps
      env:
        CC: ${{ matrix.compiler }}
      run: |
        cd build
        make check_deps VERBOSE=1
    - name: make
      env:
        CC: ${{ matrix.compiler }}
      run: |
        cd build
        make -j4 VERBOSE=1
    - name: ctest
      run: |
        cd build
        ctest -VV
