name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++, clang++]
        tls: [-DMQTT_USE_TLS=ON, -DMQTT_USE_TLS=OFF]
        exclude:
        - os: macos-latest
          compiler: g++
    steps:
    - uses: actions/checkout@v1
    - name: install boost for linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo add-apt-repository ppa:mhier/libboost-latest
        sudo apt-get update
        sudo apt-get install boost1.67
    - name: install boost for macos
      if: matrix.os == 'macos-latest'
      run: |
        brew install boost
    - name: install openssl for macos
      if: matrix.os == 'macos-latest'
      run: |
        brew install openssl
    - name: cmake
      env:
        CXX: ${{ matrix.compiler }}
      run: |
        mkdir build
        cd build
        cmake ${{ matrix.tls }} ..
    - name: make check_deps
      run: |
        cd build
        cmake --build . --target check_deps
    - name: make
      run: |
        cd build
        cmake --build .
    - name: ctest
      run: |
        cd build
        ctest -VV
