name: CI

on: [push]

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        build_selector: [-DMQTT_TEST_1=ON  -DMQTT_TEST_2=ON  -DMQTT_TEST_3=OFF -DMQTT_TEST_4=OFF -DMQTT_TEST_5=ON  -DMQTT_TEST_6=OFF -DMQTT_TEST_7=OFF -DMQTT_USE_TLS=OFF  -DMQTT_BUILD_EXAMPLES=OFF -DMQTT_USE_WS=ON, -DMQTT_TEST_1=OFF -DMQTT_TEST_2=OFF -DMQTT_TEST_3=ON  -DMQTT_TEST_4=OFF -DMQTT_TEST_5=OFF -DMQTT_TEST_6=OFF -DMQTT_TEST_7=OFF -DMQTT_USE_TLS=OFF  -DMQTT_BUILD_EXAMPLES=OFF -DMQTT_USE_WS=ON]
    steps:
    - uses: actions/checkout@v1
    - name: install boost
      run: |
        brew install boost
    - name: install openssl for macos
      if: matrix.os == 'macos-latest'
      run: |
        brew install openssl
    - name: cmake
      env:
        OPENSSL_ROOT_DIR: /usr/local/opt/openssl
        CXX: clang++
      run: |
        export
        mkdir build
        cd build
        cmake ${{ matrix.tls }} ..
    - name: make check_deps
      run: |
        cd build
        cmake --build . --target check_deps
    - name: make
      run: |
        cd build
        cmake --build .
    - name: ctest
      run: |
        cd build
        ctest -VV
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
#        tls: [-DMQTT_USE_TLS=ON, -DMQTT_USE_TLS=OFF]
        build_selector: [-DMQTT_TEST_1=ON  -DMQTT_TEST_2=ON  -DMQTT_TEST_3=OFF -DMQTT_TEST_4=OFF -DMQTT_TEST_5=ON  -DMQTT_TEST_6=OFF -DMQTT_TEST_7=OFF -DMQTT_USE_TLS=OFF  -DMQTT_BUILD_EXAMPLES=OFF -DMQTT_USE_WS=ON, -DMQTT_TEST_1=OFF -DMQTT_TEST_2=OFF -DMQTT_TEST_3=ON  -DMQTT_TEST_4=OFF -DMQTT_TEST_5=OFF -DMQTT_TEST_6=OFF -DMQTT_TEST_7=OFF -DMQTT_USE_TLS=OFF  -DMQTT_BUILD_EXAMPLES=OFF -DMQTT_USE_WS=ON]
    steps:
    - uses: actions/checkout@v1
    - name: install boost
      run: |
        sudo add-apt-repository ppa:mhier/libboost-latest
        sudo apt-get update
        sudo apt-get install boost1.67
    - name: cmake
      env:
        CXX: ${{ matrix.compiler }}
      run: |
        export
        mkdir build
        cd build
        cmake ${{ matrix.build_selector }} ..
    - name: make check_deps
      run: |
        cd build
        cmake --build . --target check_deps
    - name: make
      run: |
        cd build
        cmake --build .
    - name: ctest
      run: |
        cd build
        ctest -VV
    
